:toc:
:sectnums:
:toclevels: 5
:sectnumlevels: 5
:showcomments:
:xrefstyle: short
:icons: font
:source-highlighter: coderay
:tick: &#x2714;
:pound: &#xA3;


= COM definitions

== What is OLE? Is it the same as COM?

== What is a proxy stub?

== What is DCOM?

== Where do you find COM registrations in the registry?

=== HKEY_CLASSES_ROOT 

[quote, Microsoft]

The HKEY_CLASSES_ROOT (HKCR) key contains file name extension associations and COM class registration information such as 
ProgIDs, CLSIDs, and IIDs. It is primarily intended for compatibility with the registry in 16-bit Windows.+
+
Class registration and file name extension information is stored under both the HKEY_LOCAL_MACHINE and HKEY_CURRENT_USER keys. 
The HKEY_LOCAL_MACHINE\Software\Classes key contains default settings that can apply to all users on the local computer. The 
HKEY_CURRENT_USER\Software\Classes key contains settings that apply only to the interactive user. The HKEY_CLASSES_ROOT 
key provides a view of the registry that merges the information from these two sources. HKEY_CLASSES_ROOT also provides this 
merged view for applications designed for previous versions of Windows.


Can COM DLLs be registered in HKCU as well as HKCR?

Can you write a COM object in C#?
